name: Permadeath
version: 1.4
main: dev.itsrealperson.permadeath.Main
bootstrapper: dev.itsrealperson.permadeath.PermadeathBootstrap
loader: dev.itsrealperson.permadeath.PermadeathLoader
api-version: 1.21
folia-supported: true
authors: [ SebazCRC, vo1d_dev, ItsRealPerson ]
description: Recreación del Plugin "PermaDeath" de la serie de ElRichMC, actualizado a 1.21 (Folia).
website: https://github.com/ItsRealPerson/Permadeath

dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  permadeath.admin:
    description: Permite usar comandos de administración
    default: op

commands:
  pdc:
    description: Comando principal de Permadeath
    aliases: [ permadeath ]
