name: Permadeath
version: 1.4-PRE2
main: dev.itsrealperson.permadeath.Main
softdepend: [ WorldEdit, ProtocolLib ]
load: STARTUP
api-version: 1.21
authors: [ SebazCRC, vo1d_dev ]
description: Recreación del Plugin "PermaDeath" de la serie de ElRichMC, actualizado a 1.21.
folia-supported: true
website: https://github.com/SebazCRC
commands:
  pdc:
    description: Comando principal de Permadeath
    aliases: [ permadeath ]
